apiVersion: v1
kind: Secret
metadata:
  name: quay-credentials
  annotations:
    tekton.dev/docker-0: https://quay.io
type: kubernetes.io/basic-auth
stringData:
  # Create Robot Account with Write Permissions at https://quay.io
  username: wkulhanek+tekton
  password: 1085WYNJEW0BL21LSXBKAYK3X9MPSQW2ZZRQXU4JVSV8DE9LL1BR9O91N6L49LSX