apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: rhte-dev-image
spec:
  type: image
  params:
  - name: url
    value: image-registry.openshift-image-registry.svc:5000/1d1a-rhte-app-dev/rhte