apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: rhte-pipeline
spec:
  resources:
  - name: app-repository
    type: git
  - name: app-image
    type: image
  tasks:
  - name: build
    taskRef:
      name: s2i-nodejs
    params:
      - name: TLSVERIFY
        value: "false"
      - name: VERSION
        value: "8"
    resources:
      inputs:
      - name: source
        resource: app-repository
      outputs:
      - name: image
        resource: app-image
  - name: tag-image
    taskRef:
      name: openshift-client
    runAfter:
      - build
    params:
    - name: ARGS
      value: "tag rhte-app:latest rhte-app:$TAG -n rhte-app"
  - name: copy-image
    taskRef:
      name: skopeo
    runAfter:
      - tag-image
    params:
    - name: ARGS
      value: "copy --src-tls-verify=false docker://image-registry.openshift-image-registry.svc:5000/rhte-app/rhte-app:$TAG docker://quay.io/$QUAY_USER/rhte-app:$TAG"
  - name: deploy-image
    taskRef:
      name: patch
    runAfter:
      - copy-image
    params:
    - name: RESOURCE
      value: FederatedDeployment
    - name: RESOURCE_NAME
      value: rhte-app
    - name: NAMESPACE
      value: rhte-app
    - name: TYPE
      value: merge
    - name: PATCH
      value: '{"spec":{"template":{"spec":{"template":{"spec":{"containers":[{"env":[{"name":"CLUSTER_NAME","value":"TBD"},{"name":"IMAGE_TAG","value":"$TAG"},{"name":"PREFIX","value":"TBD"}],"image":"quay.io/$QUAY_USER/rhte-app:$TAG","name":"rhte-app", "ports":[{"containerPort":3000}]}]}}}}}}'