apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: deploy-dc
spec:
  # Use service account with git and image repo credentials
  serviceAccount: pipeline
  taskRef:
    name: openshift-client
  inputs:
    params:
    - name: ARGS
      value: "rollout latest rhte-app"
