apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: set-image
spec:
  # Use service account with git and image repo credentials
  serviceAccount: pipeline
  taskRef:
    name: openshift-client
  inputs:
    params:
    - name: ARGS
      value: "set image dc rhte-app rhte-app=image-registry.openshift-image-registry.svc:5000/1d1a-rhte-app-dev/rhte-app:test"
