apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: skopeo
spec:
  inputs:
    params:
    - name: ARGS
      description: The skopeo CLI arguments to run
      default: --help
  steps:
  - name: skopeo
    image: quay.io/wkulhanek/tekton-skopeo:0.1
    command: ["/usr/local/bin/skopeo"]
    args:
    - "${inputs.params.ARGS}"