apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: s2i-nodejs-taskrun
spec:
  # Use service account with git and image repo credentials
  serviceAccount: pipeline
  taskRef:
    name: s2i-nodejs
  inputs:
    resources:
    - name: source
      resourceRef:
        name: rhte-git
    params:
    - name: TLSVERIFY
      value: "false"
  outputs:
    resources:
    - name: image
      resourceRef:
        name: rhte-image